### ISSUE TITLE
Error in Text2Latex

### ISSUE THREAD

**Issue by Krib89** [Don-Chris/Plot2LaTeX#2]
Hi Chris,

unfortunately, your code does not work for me, both in Matlab 2020b and Matlab 2023a. I get the following error message: 
![Plot2Latex Error](https://github.com/Don-Chris/Plot2LaTeX/assets/134632036/bbb97fdf-69b9-4b34-9059-afaec2a31385)
With this simple plot: 
![Plot2Latex Error Plots](https://github.com/Don-Chris/Plot2LaTeX/assets/134632036/e8867503-d983-4533-bb97-a9705b7f43f9)
Any idea what it is?

Best regards!

**Comment by Don-Chris** [comment]
Thank you for this issue, I think I know the problem and will fix it. In the mean time you can comment out line 985-987.
