### ISSUE TITLE
Replacementlist Error

### ISSUE THREAD

**Issue by Stefanski89** [Don-Chris/Plot2LaTeX#4]
Matlab version 2021b:

For replacement lists with more than one entry, I had to add an 'any' to the If query in line 989. 

if ~isempty(opts.ReplaceList) && **any**(ismember(opts.ReplaceList(:,1),Label.TrueText{idx}))
        Label.TrueText{idx} = opts.ReplaceList{find(ismember(opts.ReplaceList(:,1),Label.TrueText{idx}),1),2};
end

Otherwise Matlab gave me the following error message: 

_Operands to the logical and (&&) and or (||) operators must be convertible to logical scalar values.
Error in Plot2LaTeX>Text2LaTeX (line 989)
    if ~isempty(opts.ReplaceList) && (ismember(opts.ReplaceList(:,1),Label.TrueText{idx}))
Error in Plot2LaTeX (line 415)
    Labels(iLabel).XMLText = Text2LaTeX(Labels(iLabel), opts);_

**Comment by Don-Chris** [comment]
@Stefanski89 Thank you for bringing this up, I think the arguments of ismember() just need to be swapped. I will fix it in the next version
